### ISSUE TITLE
[FE] 카테고리 메뉴 슬라이딩 효과

### ISSUE THREAD

**Issue by BB-choi** [ikjo93/sidedish#12]
## DESCRIPTION
카테고리 메뉴 양 쪽 버튼을 누르면 새로운 메뉴 4개가 노출되고, 더 이상 데이터가 없을 경우에는 버튼이 연한 회색으로 변경되어 표시된다.

## TASK
- [x] 더 이상 데이터가 없는 경우(카테고리 방향에 맞는 데이터를 가져올 수 없는 경우) 화살표 색은 연한 회색으로 변경되어 표시된다.
- [x] 카테고리의 화살표 버튼을 누르면 fetch요청으로 `+1` 혹은 `-1`페이지의 메뉴 정보 데이터를 가져와 state에 저장한다.
- [x] state가 변경됨에 따라 useEffect로 슬라이딩 애니메이션 효과를 보여주며 해당 버튼에 알맞은 페이지를 보여준다.
- [x] 만약 다음 슬라이드의 메뉴 개수가 4개 미만인 경우 그 갯수에 맞추어 이동한다.
