### ISSUE TITLE
[FE] 모든 카테고리 보기 버튼 동작

### ISSUE THREAD

**Issue by BB-choi** [ikjo93/sidedish#13]
## DESCRIPTION
모든 카테고리 보기버튼을 누르면 추가적인 카테고리들이 렌더링 된다.

## TASK
- [x] 모든 카테고리 보기를 누르면 추가적인 카테고리들이 렌더링 된다.
- [x] 각 컴포넌트마다 카테고리의 상품 데이터를 state로 가진다.
- [x] 각 컴포넌트마다 카테고리의 상품 데이터를 state로 가진다.
