### ISSUE TITLE
[FE] 메뉴 카드 클릭 시 상세 페이지 노출

### ISSUE THREAD

**Issue by JinJeon** [ikjo93/sidedish#20]
## DESCRIPTION

메뉴 카드 클릭 시 상세 페이지가 나온다.

## TASK

- [ ] 메뉴 카드를 클릭 시 모달이 화면 가운데 노출된다.
- [ ] 메뉴 데이터 id를 통해 서버로부터 상세 데이터를 가져와 state로 설정한다.
- [ ] 각 컴포넌트마다 카테고리의 상품 데이터를 state로 가진다.
- [ ] state로 상세 페이지의 내용을 렌더링한다.
- [ ] 닫기 버튼을 클릭 시 상세 페이지를 나간다.
- [ ] 상세 페이지 모달 외부를 클릭 시 상세 페이지를 나간다.
