### ISSUE TITLE
[FE] 헤더 생성 및 렌더링

### ISSUE THREAD

**Issue by JinJeon** [ikjo93/sidedish#4]
## DESCRIPTION
페이지가 렌더링 될 때 헤더 부분이 함께 렌더링 되며, 마우스 이벤트가 동작하도록 한다.

## TASK
- [x] 페이지 렌더링 시 헤더 부분도 함께 렌더링 된다. (하드 코딩으로 진행)
- [x] 헤더의 메뉴 부분에 마우스를 올리면 세부 목록이 적힌 레이어가 노출된다.
  - 세부 목록은 하드 코딩한다. 
- [x] 세부 목록에 마우스를 올리면 텍스트 색이 변경되고 밑줄을 생성한다.
- [x] 마우스가 세부목록 영역을 벗어나면 세부 목록 레이어가 사라진다.
