### ISSUE TITLE
[FE] 기획전 메뉴 카드 렌더링

### ISSUE THREAD

**Issue by JinJeon** [ikjo93/sidedish#6]
## DESCRIPTION
- 첫 화면 렌더링 시 기획전의 첫 번째 TAB의 메뉴를 렌더링하고, 다른 TAB을 선택할 시 메뉴를 다시 렌더링한다.
- 각 메뉴 카드의 정보로 이름, 할인 전 ∙ 후 가격, 이벤트 배지를 보여준다.

## TASK
- 카드 정보 fetch 및 state 저장
  - [x] 첫 화면 렌더링 시 기획전 첫 번째 TAB의 정보를 fetch 요청으로 받아온다.
  - [x] TAB을 누르면 해당 TAB의 정보를 fetch 요청으로 받아온다.
    - 이미 활성화된 TAB을 누를 시, 다시 fetch 요청을 보내지 않고, 리렌더링하지 않는다. 
  - [x] 가져온 TAB의 정보를 state에 담아둔다.
  - [x] 기획전 컴포넌트 부분에 state를 변경한다.

- 각 메뉴 카드의 정보 보여주기
  - [x]  상위 컴포넌트에서 넘겨받은 props를 이용하여 각 메뉴의 정보를 보여준다.
  - [x] 이름, 상세 설명 데이터를 보여준다.
  - [x] 할인 가격이 있는 경우, 할인 후 가격 → 할인 전 가격 순으로 보여준다.
  - [x] 이벤트 배지가 있는 경우 이벤트 배지를 보여준다.

**Comment by BB-choi** [comment]
자꾸 제 스스로가 메뉴부분이 탭 이름인지 카드 부분인지 헷갈려해서;;; 제목을 수정해봤습니다😅
